---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'  # Location of package manifests
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '09:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 3
    assignees:
      - "clouddrove-ci"
    reviewers:
      - "d4kverma"
      - "anmolnagpal"
  - package-ecosystem: 'terraform'
    directory: '*'  #  Location of package manifests
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '09:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 3
    assignees:
      - "clouddrove-ci"
    reviewers:
      - "d4kverma"
      - "anmolnagpal"
...
