---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/automerge.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'nlb / Get min/max versions'
...
