---
name: cloudformation-linter
on:
  workflow_call:
    inputs:
      cf_file_path:
        required: true
        type: string
        description: 'path of cloudformation template.'

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🧪 cfn-lint-action
        uses: ScottBrenner/cfn-lint-action@be676baed6db1a0d44f2f3ea59554623dc5b4109 # v2.4.9
        with:
          command: cfn-lint -t ${{ inputs.cf_file_path }}

      - name: 🔒 cfn security checks
        uses: minchao/cfn-nag-action@7a57ff47a03f87c7ea82265d96423a4182fde35f # v0.1
        with:
          args: '--input-path ${{ inputs.cf_file_path }}'
...
