---
name: Checkov Security Scan

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      continue_on_error:
        required: true
        type: string
        default: 'true'
      var_file:
        required: false
        type: string
      skip_check:
        required: false
        type: string
        default: ''
      output_format:               
        required: false
        type: string
        default: 'cli,sarif'
      output_file_path:       
        required: false
        type: string
        default: 'console,results.sarif'


permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup Old SARIF
        run: rm -f results.sarif || true

      - name: Run Checkov (Docker-based)
        id: checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.directory }}
          framework: terraform
          soft_fail: ${{ inputs.continue_on_error == 'true' }}
          var_file: ${{ inputs.var_file }}
          download_external_modules: false
          skip_check: ${{ inputs.skip_check }}
          output_format: ${{ inputs.output_format }}
          output_file_path: ${{ inputs.output_file_path }}

      - name: Upload SARIF to GitHub Security
        if: always() && !cancelled()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: checkov

      - name: Comment on PR with Checkov results
        if: github.event_name == 'pull_request'
        uses: clouddrove/checkov-sarif-view@v0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sarif_file: results.sarif

      - name: Fail if Issues Found
        if: always() && github.event_name == 'pull_request'
        run: |
          ISSUE_COUNT=$(jq '.runs[0].results | length' results.sarif)
          echo "Checkov Issue Count: $ISSUE_COUNT"
          if [ "$ISSUE_COUNT" -gt 0 ]; then
            echo "::error::Checkov found $ISSUE_COUNT security issues. Failing the workflow."
            exit 1
          fi
...
