---
name: Claude PR Review Checks

on:
  workflow_call:
    inputs:
      branch:
        description: 'Specify the branch if needed'
        required: false
        type: string
    secrets:
      ANTHROPIC_API_KEY:
        description: 'Anthropic API Key'
        required: true

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  # Regular PR Checks
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

  # Claude AI feedback
  claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Automatic PR Review
        uses: anthropics/claude-code-action@v1-dev
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Please review this pull request and provide comprehensive feedback.

            Focus on:
              - Code quality and best practices
              - Potential bugs or issues
              - Performance considerations
              - Security implications
              - Test coverage
              - Documentation updates if needed

            Provide constructive feedback with specific suggestions for
            improvement.
            Use inline comments to highlight specific areas of concern.
...
