---
name: CloudFormation Stack Creation
on:
  workflow_call:
    inputs:
      aws-region:
        description: 'AWS region for the stack'
        required: true
        type: string
        default: 'us-east-2'
      stack-name:
        description: 'CloudFormation stack name'
        required: true
        type: string
      template-url:
        description: 'S3 URL of the CloudFormation template'
        required: true
        type: string
      parameter-overrides:
        description: 'The parameters to override in the stack inputs as a JSON array'
        required: false
        type: string
      capabilities:
        description: "The comma-delimited list of stack template capabilities to acknowledge. Defaults to 'CAPABILITY_IAM'"
        required: false
        default: "CAPABILITY_NAMED_IAM"
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_ROLE_TO_ASSUME:
        required: false
        description: 'AWS Role ARN defined'
      GITHUB:
        required: false
        description: 'GitHub token'
      parameter-overrides:
        description: 'The parameters to override in the stack inputs. You can pass a comma-delimited list or a file URL. The comma-delimited list has each entry formatted as <ParameterName>=<ParameterValue> or <ParameterName>="<ParameterValue>,<ParameterValue>".'
        required: false

jobs:
  deploy-cf-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Check if Stack exists
        id: check-stack
        run: |
          set +e
          aws cloudformation describe-stacks --stack-name ${{ inputs.stack-name }}
          echo "STACK_EXISTS=$?" >> $GITHUB_ENV
          set -e

      - name: Create or Update Stack
        run: |
          if [ "${STACK_EXISTS}" == "0" ]; then
            echo "Updating existing CloudFormation stack..."
            aws cloudformation update-stack \
              --stack-name ${{ inputs.stack-name }} \
              --template-url ${{ inputs.template-url }} \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameters ${{ secrets.parameter-overrides }}
          else
            echo "Creating new CloudFormation stack..."
            aws cloudformation create-stack \
              --stack-name ${{ inputs.stack-name }} \
              --template-url ${{ inputs.template-url }} \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameters ${{ secrets.parameter-overrides }}
          fi
...