---
name: docker-scout
on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      COMPARE_TAG:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: 'dockerhub username'
        required: true
      DOCKERHUB_PASSWORD:
        description: 'dockerhub password'
        required: true
      TOKEN:
        description: 'Github Token'
        required: true

jobs:
  docker-scout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker image
        env:
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
          images: ${{ inputs.images }}
        run: |
          docker build -t $images:$IMAGE_TAG .
          # docker push $images:$IMAGE_TAG

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          to-latest: false
          to: ${{ inputs.images }}:${{ inputs.COMPARE_TAG }}
          image: ${{ inputs.images }}:${{ inputs.IMAGE_TAG }}
          ignore-base: false
          ignore-unchanged: true
          only-fixed: false
          write-comment: true
          github-token: ${{ secrets.TOKEN }}
