name: HELM

on:
  workflow_call:
    inputs:
      provider:
        required: true
        type: string
        description: 'Cloud provider to run the workflow. e.g. azure or aws'
      eks-cluster-name:
        required: false
        type: string
        description: 'EKS cluster name'
      aws-region:
        required: false
        type: string
        description: 'AWS EKS cluster region'
      azure-cluster-name:
        required: false
        type: string
        description: 'Azure cluster name'
      resource-group:
        required: false
        type: string
        description: 'Container for managing Azure resources'
      helm-chart-directory:
        required: true
        type: string
        description: 'Kubernetes deployment configurations files'
      release-name:
        required: false
        type: string
        description: 'Unique ID for installed chart'
      timeout:
         required: true
         type: string
         description: 'Timeout for helm install step in seconds'
         default: '120s'
      set-parameters:
        required: false
        type: string 
        description: 'Overriding the default values'
      values-file-path: 
        required: true
        type: string
        description: 'Values file path from helm chart directory'
      history-max: 
        required: true
        type: number
        description: 'number of revisions stored in the revision history.'
        default: '7'
      namespace:
        required: false
        type: string
        description: 'Boundary for Kubernetes resources'
      rollback:
         required: false
         type: string
         description: 'Environment name for rollback'
    secrets:
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: false
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: false
      AZURE_CREDENTIALS:
        description: 'Azure Credentilas'
        required: false
jobs:
  helm-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        if: ${{ inputs.provider == 'aws' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Install Azure CLI
        if: ${{ inputs.provider == 'azure' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Kubeconfig
        run: |
          if [ "${{ inputs.provider }}" = "azure" ]; then
            az aks get-credentials --resource-group ${{ inputs.resource-group }} --name ${{ inputs.azure-cluster-name }}
          else 
            aws eks --region ${{ inputs.aws-region }} update-kubeconfig --name ${{ inputs.eks-cluster-name }}
          fi
      
      - name: helm lint
        if: ${{ inputs.rollback != 'rollback' }}
        run: |
          helm lint ${{ inputs.helm-chart-directory }}
          
      - name: helm template
        if: ${{ inputs.rollback != 'rollback' }}
        run: |
          helm template ${{ inputs.helm-chart-directory }}
          
      - name: helm install and upgrade2
        if: ${{ inputs.rollback != 'rollback' }}
        run: |
          if [ -n "${{ inputs.set-parameters }}" ]; then
            helm upgrade --install --atomic --create-namespace --wait --history-max ${{ inputs.history-max }} --debug \
              ${{ inputs.release-name }} ${{ inputs.helm-chart-directory }} ${{ inputs.set-parameters }} -f ${{ inputs.values-file-path }} --namespace=${{ inputs.namespace }} --timeout ${{ inputs.timeout }}
          else
            helm upgrade --install --atomic --create-namespace --wait --history-max ${{ inputs.history-max }} --debug \
              ${{ inputs.release-name }} ${{ inputs.helm-chart-directory }} -f ${{ inputs.values-file-path }} --namespace=${{ inputs.namespace }} --timeout ${{ inputs.timeout }}
          fi
                                                                                                               
      - name: Rollback Helm Release
        if: ${{ inputs.rollback == 'rollback' }}
        run: |
            helm rollback ${{ inputs.release-name }} -n ${{ inputs.namespace }} 
