---
name: Assignees

on:
  workflow_call:
    inputs:
      assignees:
        description: 'A list of assignees(GitHub user name) to be added to PR'
        required: true
        type: string
      reviewers:
        description: 'A list of reviewers(GitHub user name) to be added to PRs'
        required: false
        type: string
      assign_yourself:
        description: 'Whether to assign the PR opener as an assignee'
        required: false
        type: boolean
        default: true
    secrets:
      GITHUB:
        description: 'Your GitHub token for authentication.'
        required: true

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          assignees: ${{ inputs.assignees }}
          reviewers: ${{ inputs.reviewers }}
          skipKeywords: wip, draft

      - uses: actions/github-script@v7
        if: ${{ inputs.assign_yourself }}
        with:
          github-token: ${{ secrets.GITHUB }}
          script: |
            const opener = context.payload.pull_request.user.login;

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees:[ opener ] 
            });
...
