---
name: changelog
permissions: write-all
on:
  push: 
    tags:
      - '*'
  workflow_dispatch:
jobs:
  changelog:
    uses: ./.github/workflows/release-changelog.yml
    with:
      branch: 'master'
      tag_format: X.Y.Z
      release_tag: ${{ github.ref_name }}
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
...
