---
name: Update Major Tag

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Extract major version
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}

          echo "Release tag: $TAG"

          # Extract major version from X.Y.Z
          MAJOR=$(echo "$TAG" | cut -d. -f1)

          MAJOR_TAG="v$MAJOR"

          echo "Major tag: $MAJOR_TAG"

          echo "major_tag=$MAJOR_TAG" >> $GITHUB_OUTPUT

      - name: Update major tag
        run: |
          git tag -f ${{ steps.version.outputs.major_tag }} ${{ github.ref_name }}

      - name: Push major tag
        run: |
          git push origin ${{ steps.version.outputs.major_tag }} --force
...