name: Smurf Reusable Workflow
on:
  workflow_call:
    secrets:
      docker-username:
        description: 'Docker Hub username'
        required: false
      docker-password:
        description: 'Docker Hub token'
        required: false
    inputs:
      tools:
        description: 'Tool to run (helm or docker)'
        type: string
        required: true
      branch:
        description: 'Branch to checkout'
        type: string
        default: 'selm'
      aws-role:
        description: 'AWS IAM role ARN to assume'
        type: string
        required: true
      aws-region:
        description: 'AWS region'
        type: string
        default: 'us-east-1'
      # Helm-specific inputs
      eks-cluster:
        description: 'EKS cluster name'
        type: string
        required: false
      ecr-repository:
        description: 'ECR repository URL'
        type: string
        required: false
      dockerfile-path:
        description: 'Path to Dockerfile'
        type: string
        required: false
      helm-values-path:
        description: 'Path to Helm values file'
        type: string
        required: false
      helm-chart-path:
        description: 'Path to Helm chart'
        type: string
        required: false
      namespace:
        description: 'Kubernetes namespace'
        type: string
        default: 'testing-smurf'
      timeout:
        description: 'Helm timeout in seconds'
        type: number
        default: 30
      # Docker-specific inputs
      image-name:
        description: 'Docker image name'
        type: string
        required: false
      image-tag:
        description: 'Docker image tag'
        type: string
        required: false

jobs:
  smurf-helm:
    if: inputs.tools == 'helm'
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4.1.7
        
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role }}
          aws-region: ${{ inputs.aws-region }}
          
      - name: Set environment variables
        run: |
          echo "AWS_DEFAULT_REGION=${{ inputs.aws-region }}" >> $GITHUB_ENV
          echo "EKS_CLUSTER_NAME=${{ inputs.eks-cluster }}" >> $GITHUB_ENV
      
      - name: Smurf SDKR Provision
        uses: clouddrove/smurf@feat/docs_format
        with:
          tool: sdkr
          command: provision-ecr ${{ inputs.ecr-repository }}:${{ github.run_id }} -f ${{ inputs.dockerfile-path }}
          
      - name: Smurf SELM Upgrade
        uses: clouddrove/smurf@feat/docs_format
        with:
          tool: selm
          command: upgrade smurf --install --atomic --set image.tag=${{ github.run_id }} -f ${{ inputs.helm-values-path }} ${{ inputs.helm-chart-path }} -n ${{ inputs.namespace }} --timeout ${{ inputs.timeout }}

  smurf-docker:
    if: inputs.tools == 'docker'
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      DOCKER_USERNAME: ${{ secrets.docker-username }}
      DOCKER_PASSWORD: ${{ secrets.docker-password }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role }}
          role-session-name: aws-auth
          aws-region: ${{ inputs.aws-region }}
          
      - name: Smurf sdkr build
        uses: clouddrove/smurf@feat/docs_format
        with:
          tool: sdkr
          command: build ${{ inputs.image-name }}:${{ inputs.image-tag }}
          
      - name: Smurf sdkr push image
        uses: clouddrove/smurf@feat/docs_format
        with:
          tool: sdkr
          command: push hub ${{ secrets.docker-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
