name: Smurf Reusable Workflow
on:
  workflow_call:
    inputs:
      tools:
        description: 'Tool to run (helm or terraform)'
        type: string
        required: true
      aws-role:
        description: 'AWS IAM role ARN to assume'
        type: string
        required: true
      aws-region:
        description: 'AWS region'
        type: string
        default: 'us-east-1'
      # Helm-specific inputs
      eks-cluster:
        description: 'EKS cluster name'
        type: string
        required: false
      ecr-repository:
        description: 'ECR repository URL'
        type: string
        required: false
      dockerfile-path:
        description: 'Path to Dockerfile'
        type: string
        required: false
      helm-values-path:
        description: 'Path to Helm values file'
        type: string
        required: false
      helm-chart-path:
        description: 'Path to Helm chart'
        type: string
        required: false
      namespace:
        description: 'Kubernetes namespace'
        type: string
        default: 'testing-smurf'
      timeout:
        description: 'Helm timeout in seconds'
        type: number
        default: 30
      # Terraform-specific inputs
      terraform-path:
        description: 'Path to terraform directory'
        type: string
        default: 'terraform'

jobs:
  terraform:
    if: inputs.tools == 'terraform'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Set AWS Region
        run: |
          echo "AWS_DEFAULT_REGION=${{ inputs.aws-region }}" >> $GITHUB_ENV

      - name: Smurf STF Init
        uses: clouddrove/smurf@master
        with:
          path: ${{ inputs.terraform-path }}
          tool: stf
          command: init

      - name: Smurf STF Validate
        uses: clouddrove/smurf@master
        with:
          path: ${{ inputs.terraform-path }}
          tool: stf
          command: validate
          
      - name: Smurf STF Plan
        uses: clouddrove/smurf@master
        with:
          path: ${{ inputs.terraform-path }}
          tool: stf
          command: plan
          
      - name: Smurf STF Apply
        uses: clouddrove/smurf@master
        with:
          path: ${{ inputs.terraform-path }}
          tool: stf
          command: apply

  helm:
    if: inputs.tools == 'helm'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Set environment variables for Helm
        run: |
          echo "AWS_DEFAULT_REGION=${{ inputs.aws-region }}" >> $GITHUB_ENV
          echo "EKS_CLUSTER_NAME=${{ inputs.eks-cluster }}" >> $GITHUB_ENV
      
      - name: Smurf SDKR Provision
        uses: clouddrove/smurf@feat/docs_format
        with:
          tool: sdkr
          command: provision-ecr ${{ inputs.ecr-repository }}:${{ github.run_id }} -f ${{ inputs.dockerfile-path }}
          
      - name: Smurf SELM Upgrade
        uses: clouddrove/smurf@feat/docs_format
        with:
          tool: selm
          command: upgrade smurf --install --atomic --set image.tag=${{ github.run_id }} -f ${{ inputs.helm-values-path }} ${{ inputs.helm-chart-path }} -n ${{ inputs.namespace }} --timeout ${{ inputs.timeout }}
