name: Smurf Reusable Workflow
on:
  workflow_call:
    inputs:
      tools:
        description: 'List of tools to run (helm,terraform)'
        type: string
        default: ''
      branch:
        description: 'Branch to checkout'
        type: string
        default: 'selm'
      aws-role:
        description: 'AWS IAM role ARN to assume'
        type: string
        required: true
      aws-region:
        description: 'AWS region'
        type: string
        default: 'us-east-1'
      eks-cluster:
        description: 'EKS cluster name'
        type: string
        required: false
      ecr-repository:
        description: 'ECR repository URL'
        type: string
        required: false
      dockerfile-path:
        description: 'Path to Dockerfile'
        type: string
        required: false
      helm-values-path:
        description: 'Path to Helm values file'
        type: string
        required: false
      helm-chart-path:
        description: 'Path to Helm chart'
        type: string
        required: false
      namespace:
        description: 'Kubernetes namespace'
        type: string
        default: 'testing-smurf'
      timeout:
        description: 'Helm timeout in seconds'
        type: number
        default: 30
      terraform-path:
        description: 'Path to terraform directory'
        type: string
        default: 'terraform'

jobs:
  smurf-helm:
    if: contains(inputs.tools, 'helm')
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v2.3.4
        
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role }}
          aws-region: ${{ inputs.aws-region }}
          
      - name: Set environment variables
        run: |
          echo "AWS_DEFAULT_REGION=${{ inputs.aws-region }}" >> $GITHUB_ENV
          echo "EKS_CLUSTER_NAME=${{ inputs.eks-cluster }}" >> $GITHUB_ENV
      
      - name: Smurf SDKR Provision
        uses: clouddrove/smurf@feat/docs_format
        with:
          tool: sdkr
          command: provision-ecr ${{ inputs.ecr-repository }}:${{ github.run_id }} -f ${{ inputs.dockerfile-path }}
          
      - name: Smurf SELM Upgrade
        uses: clouddrove/smurf@feat/docs_format
        with:
          tool: selm
          command: upgrade smurf --install --atomic --set image.tag=${{ github.run_id }} -f ${{ inputs.helm-values-path }} ${{ inputs.helm-chart-path }} -n ${{ inputs.namespace }} --timeout ${{ inputs.timeout }}

  smurf-terraform:
    if: contains(inputs.tools, 'terraform')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Smurf STF Init
        uses: clouddrove/smurf@master
        with:
          path: ${{ inputs.terraform-path }}
          tool: stf
          command: init

      - name: Smurf STF Validate
        uses: clouddrove/smurf@master
        with:
          path: ${{ inputs.terraform-path }}
          tool: stf
          command: validate
      - name: Smurf STF plan
        uses: clouddrove/smurf@master
        with:
          path: ${{ inputs.terraform-path }}
          tool: stf
          command: plan
      - name: Smurf STF apply
        uses: clouddrove/smurf@master
        with:
          path: ${{ inputs.terraform-path }}
          tool: stf
          command: apply      
