---
name: AWS SSM Send-Command
on:
  workflow_call:
    inputs:
      COMMAND:
        description: 'This action helps you to execute remote bash command for AWS EC2 instance without SSH or other accessing.'
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
        description: 'AWS Access Key ID to install AWS CLI.'
      AWS_SECRET_ACCESS_KEY:
        required: false
        description: 'AWS Secret access key to install AWS CLI'
      INSTANCE_ID:
        required: false
        description: 'To get the instance ID of a running instance'

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        id: ssm
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}
          comment: aws-ssm-send-command testing
          working-directory: /home/ubuntu/
          command: ${{ inputs.COMMAND }}
...
