name: Shared Workflow - sst-deploy

on:
  workflow_call:
    inputs:
      app-env:
        description: 'Application environment'
        required: false
        type: string
        default: 'stag'
      working-directory:
        description: 'working directory in repo'
        required: true
        type: string
      preview:
        description: 'Create or Destroy preview env'
        required: true
        type: string
    secrets:
      aws-access-key-id-prod:
        description: 'aws access keys of prod'
        required: true
      aws-secret-access-key-prod:
        description: 'aws secret access keys of prod'
        required: true
      aws-access-key-id-stag:
        description: 'aws access keys of stag'
        required: true
      aws-secret-access-key-stag:
        description: 'aws secret access keys of stag'
        required: true

jobs:
  sst-deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
        
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials (PROD ACCOUNT)
        if: ${{ inputs.app-env == 'PROD' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id-prod }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key-prod }}
          aws-region: us-west-2

      - name: Configure AWS credentials (STAG ACCOUNT)
        if: ${{ inputs.app-env == 'STAG' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id-stag }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key-stag }}
          aws-region: us-west-2

      - name: Install dependencies (npm install)
        run: npm install
          
      - name: Install dependencies (npm ci)
        run: npm ci
          
      - name: Build preview app
        if: ${{ inputs.preview == 'create' }}
        run: npx sst build --stage ${{ inputs.app-env }}
          
      - name: Deploy preview app
        if: ${{ inputs.preview == 'create' }}
        run: npx sst deploy --stage ${{ inputs.app-env }}
          

      - name: Remove preview app
        if: ${{ inputs.preview == 'destroy' }}
        run: npx sst remove --stage ${{ inputs.app-env }}


