name: 'Terratest GitHub Actions'
on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory where main.tf exist of the module.'
        required: false
        type: string
        default: './_example/'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Terraform Format'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'fmt'

      - name: 'Terraform init'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ${{ inputs.working_directory}}

      - name: 'Terraform validate'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ inputs.working_directory}}

      - name: 'Terraform plan'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ inputs.working_directory}}