---
# 🧪 Tflint workflow checks for possible errors, and best practices in your terraform code
name: tf-lint
on:
  workflow_call:
    secrets:
      GITHUB:
        required: true
        description: 'PAT of the user to run the jobs.'

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v6

      - name: 💾 Cache plugin dir
        uses: actions/cache@v5
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: ⚙️ Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.44.1
          github_token: ${{ secrets.GITHUB }}

      - name: 🛠️ Setup tflint-config
        uses: terraform-linters/tflint-load-config-action@v2
        with:
          source-repo: clouddrove/github-shared-workflows
          source-path: .github/config/.tflint.hcl
          source-ref: master

      - name: 🔍 Show version
        run: tflint --version

      - name: 🚀 Init lint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: ✅ Run lint
        run: tflint --recursive --color --force -f compact
        env:
          GITHUB_TOKEN: ${{ github.token }}
...
