---
name: 🧾 YAML-LINTER
on:
  workflow_call:
jobs:
  Yaml-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🔍 yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_data: |
            rules:
              line-length:
                max: 450
                level: warning
              comments-indentation:
                 level: error
              indentation:
                  level: error
              trailing-spaces:
                  level: error
              new-line-at-end-of-file:
                  level: error
              document-start:
                  level: error
              document-end:
                  level: error
              key-duplicates:
                  level: error
              braces:
                  level: error
              brackets:
                  level: error
              colons:
                  level: error
              commas:
                  level: error
              comments:
                  level: error
              empty-lines:
                  level: error
              empty-values:
                  level: warning
              float-values:
                  level: error
              hyphens:
                  level: error
...
